config/routes.rb
Rails.application.routes.draw do
  root to: 'list#index'

  resources :users do
    put :add_r, :remove_r, :toggle_done
  end
  resources :list, only: [:index]
  resource :session, only: [:new, :create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates_uniqueness_of :username
  validates_confirmation_of :password
  after_initialize :ensure_session_token

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def self.ordered_list
    User.all.order(rejections: :desc)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def self.total_r
    User.all.sum(:rejections)
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout_user
    current_user.reset_session_token!
    session[:session_token] = nil
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if user
      login_user(user)
      redirect_to list_index_url
    else
      flash.now[:errors] = ["Username/Password combination is incorrect"]
      render :new
    end
  end

  def destroy
    logout_user
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
require 'set'

class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login_user(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to list_index_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to list_index_url
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to list_index_url
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to list_index_url
    end
  end

  def add_r
    @user = User.find(params[:user_id])
    @user.increment!(:rejections)
    redirect_to list_index_url
  end

  def remove_r
    @user = User.find(params[:user_id])
    @user.decrement!(:rejections)
    redirect_to list_index_url
  end

  def all_cohorts
    @users = User.all()
    @cohorts = Set.new
    @users.each do |user|
      @cohorts.add(user.startdate)
    end
    @cohorts
  end

  def toggle_done
    @user = User.find(params[:user_id])
    @user.update(done: !@user.done)
    redirect_to list_index_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :display_name, :password, :password_confirmation, :color, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wall of Minor Obstacles</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" type="image/x-icon" href="/assets/favicon.ico">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'></head>
<body>

  <div class="content">
    <%= button_to("Home", root_url, method: :get, class: "button") %>
    <span class="profile-buttons">
      <% if current_user %>
        <h4><%= current_user.username %></h4>
        <%= button_to("Sign Out", session_url, method: :delete, class: "button") %>
        <%= button_to("Edit Profile", edit_user_url(current_user), method: :get, class: "button") %>
      <% else %>
        <%= button_to("Sign Up", new_user_url, method: :get, class: "button") %>
        <%= button_to("Sign In", new_session_url, method: :get, class: "button") %>
      <% end %>
    </span>
  <%= yield %>
</div>

</body>
</html>

app/views/list/index.html.erb
<h1 class="title">Wall of Minor Obstacles</h1>
<h1 class="cohort">
  Cohort Start Date:
  <select class="cohort" name="startdate">
    <% User.all_cohorts.each do |startdate| %>
      
    <% end %>
  </select>
</h1>
<h1 class="total">Total: <%=User.total_r%></h1>
<h2 class="list-top">&lt;ul&gt;</h2>
<% User.ordered_list.each do |user| %>
  <h2 class="list-item" style="color:<%= user.color %>;">
    &lt;li&gt;
    <span class="name"
          style="text-decoration: <%= user.done ? 'line-through' : 'none' %>">
      <%= user.display_name == "" || !user.display_name ? user.username : user.display_name %>:</span>
    <% count = user.rejections %>
    <% if count == 0 %>
      0
    <% end %>
    <% if count != 0  && user == current_user%>
      <%= button_to "-", user_remove_r_url(user.id), method: :put, class: "add-remove" %>
    <% end %>
    <% while count >= 5  %>
      <%= image_tag "5tally.png", class: "tally", style:"background-color: #{user.color}"%>
      <% count -= 5 %>
    <% end %>
    <% tally_img = case count %>
      <% when 4 then "4tally.png" %>
      <% when 3 then "3tally.png" %>
      <% when 2 then "2tally.png" %>
      <% when 1 then "1tally.png" %>
    <% end %>
    <%= image_tag tally_img, class: "tally", style:"background-color: #{user.color}" %>
    <% if user == current_user %>
      <%= button_to "+", user_add_r_url(user.id), method: :put, class: "add-remove" %>
    <% end %>
    &lt;/li&gt;
    <% if user == current_user %>
      <%= button_to "Done?", user_toggle_done_url(user.id), method: :put, class: "add-remove" %>
    <% end %>
  </h2>
<% end %>

<h2>&lt;/ul&gt;</h2>

app/views/users/edit.html.erb
<form class="user-auth" action=<%= user_url(@user) %> method="post">
  <h1>
    Edit Profile -
    <%= link_to "Delete Account", user_url(@user), 'data-method' => :delete, 'data-confirm' => "Are you sure?", class: "delete"%>
  </h1>
  <% if flash[:errors] %>
    <p class="errors">
      <% flash[:errors].each do |error| %>
        <%= error %> <br>
      <% end %>
    </p>
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  <h3>
    <label for="display_name">
      Display Name:
      <input class="input" type="text" name=user[display_name] value="<%= @user.display_name %>" id="display_name">
    </label>
  </h3>
  <h3>
    <label for="startdate">
      Cohort Start Date:
      <input type="date" name="startdate" value="<%= @user.startdate %>">
    </label>
  </h3>
  <h3>
    <label for="color">
      Marker Color:
      <input class="input" type="color" name=user[color] value="<%= @user.color %>" id="color">
    </label>
  </h3>
  <input class="button" type="submit" name="name" value="Submit Changes">
  <%= link_to "cancel", list_index_url %>
</form>

app/views/users/new.html.erb
<form class="input-group user-auth" action=<%= users_url %> method="post">
  <h1>Sign Up</h1>

  <% if flash[:errors] %>
    <p class="errors">
      <% flash[:errors].each do |error| %>
        <%= error %> <br>
      <% end %>
    </p>
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <h3>
    <label for="username">
      Username:
      <input class="input" type="text" name=user[username] value="" id="username">
    </label>
  </h3>
  <h3>
    <label for="password">
      Password:
      <input class="input" type="password" name=user[password] value="" id="password">
    </label>
  </h3>
  <h3>
    <label for="confirm_password">
      Confirm Password:
      <input class="input" type="password" name="user[password_confirmation]" id="confirm_password" value="">
    </label>
  </h3>
  <input class="button" type="submit" name="name" value="Sign Up">
  <br>
  <p class="switch">
    <%= link_to "Already have an account? Sign in", new_session_url %>
  </p>
</form>